### ISSUE TITLE
Images are not displayed on mobile browsers

### ISSUE THREAD

**Issue by forsurefr** [Ervie/Seiyuu.moe#12]
Hello. 
When browsing the site using a mobile browser (even in desktop mode) the images for the compare are not displayed. In desktop browsers it is working.

**Comment by Ervie** [comment]
Hi, this decision was made consciously due to two factors:

- when using mobile device, there's high chance the user is not using wi-fi and limiting data send to the device will lesser the usage of data limit for the device.
- loading images in the smaller screen did not work so great.

Currently, the website starts displaying images when the width of display screen is at least 1264 pixels, otherwise it uses text mode. Screen resolution on the mobiles is usually calculated in a bit different way (3 pixels counted as one), therefore width condition is not fulfilled and website stays in text mode.

I will give it a thought if we can keep images in desktop mode for mobile browsers, or shrink the images.

**Comment by forsurefr** [comment]
Maybe an option to display images (which is set to false by default) when comparing could work.
It would really help if images are displayed on mobile as well.

**Comment by Ervie** [comment]
I gave it a shot and reworked mobile comparisons + timeline. now they have images.

I will think about option for hiding images for those who do not want to load images while on mobile.
